import Head from 'next/head'
import styles from '../styles/Home.module.css'
import Botao from '../components/botão'
import { useContext } from 'react'

let result = 0

const Calculator = () => {
  result = 0
}

const icon = <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" strokeWidth={1.5} stroke="currentColor" className="w-6 h-6">
<path strokeLinecap="round" strokeLinejoin="round" d="M15.75 15.75V18m-7.5-6.75h.008v.008H8.25v-.008zm0 2.25h.008v.008H8.25V13.5zm0 2.25h.008v.008H8.25v-.008zm0 2.25h.008v.008H8.25V18zm2.498-6.75h.007v.008h-.007v-.008zm0 2.25h.007v.008h-.007V13.5zm0 2.25h.007v.008h-.007v-.008zm0 2.25h.007v.008h-.007V18zm2.504-6.75h.008v.008h-.008v-.008zm0 2.25h.008v.008h-.008V13.5zm0 2.25h.008v.008h-.008v-.008zm0 2.25h.008v.008h-.008V18zm2.498-6.75h.008v.008h-.008v-.008zm0 2.25h.008v.008h-.008V13.5zM8.25 6h7.5v2.25h-7.5V6zM12 2.25c-1.892 0-3.758.11-5.593.322C5.307 2.7 4.5 3.65 4.5 4.757V19.5a2.25 2.25 0 002.25 2.25h10.5a2.25 2.25 0 002.25-2.25V4.757c0-1.108-.806-2.057-1.907-2.185A48.507 48.507 0 0012 2.25z" />
</svg>


export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Calculator</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/iconcalc.png" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Calculator using <a href="https://nextjs.org">Next.js!</a>
        </h1>

        <section className='visor'>
        <div className="calculator__creen">
          <h1 className={styles.resultado}>{result}</h1>
        </div>
        </section>
        <section className='calculator_keys'>
          <div className={styles.divisoes}>
            <Botao valor="C" tipo='clean' />
            <Botao valor="%" tipo='operator' />
            <Botao valor="/" tipo='operator' />
          </div>
          <div className={styles.divisoes}>
            <Botao valor="7" tipo='number' />
            <Botao valor="8" tipo='number' />
            <Botao valor="9" tipo='number' />
            <Botao valor="x" tipo='operator' />
          </div>
          <div className={styles.divisoes}>
            <Botao valor="4" tipo='number' />
            <Botao valor="5" tipo='number' />
            <Botao valor="6" tipo='number' />
            <Botao valor="-" tipo='operator' />
          </div>
          <div className={styles.divisoes}>
            <Botao valor="1" tipo='number' />
            <Botao valor="2" tipo='number' />
            <Botao valor="3" tipo='number' />
            <Botao valor="+" tipo='operator' />
          </div>
          <div className={styles.divisoes}>
            <Botao valor="+/-" tipo='operator' />
            <Botao valor="0" tipo='number' />
            <Botao valor="," tipo='number' />
            <Botao valor="=" tipo='result' />
          </div>
        </section>
      </main>

      <footer className={styles.footer}>
        <a
          href="" target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' @caiocubeiro '}
        </a>
      </footer>
    </div>
  )
}
