import Head from 'next/head'
import styles from '../styles/Home.module.css'
import Botao from '../components/botão'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Calculator using <a href="https://nextjs.org">Next.js!</a>
        </h1>

        <section className='visor'>

        </section>
        <section className='teclas'>
          <div className={styles.divisoes}>
            <Botao valor="C" tipo='clean' />
            <Botao valor="%" tipo='operator' />
            <Botao valor="/" tipo='operator' />
          </div>
          <div className={styles.divisoes}>
            <Botao valor="1" tipo='clean' />
            <Botao valor="2" tipo='operator' />
            <Botao valor="3" tipo='operator' />
          </div>
        </section>
      </main>

      <footer className={styles.footer}>
        <a
          href="" target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' @caiocubeiro '}
        </a>
      </footer>
    </div>
  )
}
